### ISSUE TITLE
Meetup API returns empty JSON

### ISSUE THREAD

**Issue by frankV** [boulder-python/boulderpython.org#11]
The Meetup API will occasionally return an empty JSON, so we either need to cache it more aggressively, or store a successful response in database as a fallback.

**Comment by svvitale** [comment]
@frankV what do you think about using a simple module variable for fallback (i.e. store the last successful result as a module variable)?  If the issue is truly intermittent and somewhat rare, it seems like doing the work to put it in the database is overkill.

**Comment by frankV** [comment]
Yea I agree. we can cache it longer too, I switched us to: http://pythonhosted.org/Flask-Caching/
