### ISSUE TITLE
Minor UI/UX improvements and corrections

### ISSUE THREAD

**Issue by svvitale** [boulder-python/boulderpython.org#15]
A few nitpicky things I noticed on the redesign:

1. Need favicon
1. Times from Meetup are displayed as GMT
1. "Twiiter" miss-spelling in Quick Links
1. Link to latest Pycon Code of Conduct: https://us.pycon.org/2018/about/code-of-conduct/

**Comment by frankV** [comment]
- [x] Need favicon
- [X] "Twiiter" miss-spelling in Quick Links
- [X] Link to latest Pycon Code of Conduct: https://us.pycon.org/2018/about/code-of-conduct/
- [X] Times from Meetup are displayed as GMT, _note: I only changed the timezone on Heroku_
